# Generated by Django 4.0.5 on 2022-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_first', '0003_rename_title_blogpost_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(),
        ),
    ]
